package com.skills4testing.core.fault;

import com.skills4testing.core.message.MsgConst;

final class CFaultConstant {

	// Uses Default constructor

	/*
	 * Message Family : Codes
	 * 
	 * Connection : 1000 Crypto : 1200 Common : 1400 //e.g. InvalidSession Fault
	 * Users : 2000 DirServers : 3000 TargetGroups : 4000 Projects : 5000
	 * Dialogues : 5400 Invitations : 5600 Reminder : 5800 Results : 6000
	 * Respondents : 6200 Destination DB : 7000 Template : 7200
	 */

	/**
	 * This methods defines the Fault constant. Method has no modfier. Can be
	 * called only by its package class. Order should be in the following order
	 * when constructing array: Error ID Description Possible Solution Details
	 * Error
	 * 
	 * @return String array list.
	 * @see setFaultErrors() //(CFault)
	 */
	static final String[][] FAULT_LIST = {

			// {"Error ID", "Description......", "Possible solution.......",
			// "Details error"}

			// Connection Faults (1000 - 1199) Class: CConncetionFaults
			{ "1000", "Write Description con", "Write possible solutions",
					"Details Error" },
			{ "1001", "Inactive User.",
					"Please inform the administrator to make the user active.",
					" Inactive user is not allowed to login." },
			{ "1002", "Invalid login.",
					"Please try to login with right user ID and Password.",
					" Username or password may be incorrect for login." },
			{ "1003", "Write Description con.", "Write possible solutions.",
					"Details Error." },

			// Crypto Faults (1200 - 1399) Class: CConncetionFaults
			{ "1200", "Write Description crypto.", "Write possible solutions.",
					"Details Error." },
			// Common Faults (1400 - 1599) Class: CFault (Base class)
			{ "1400", "Write Description for Common.",
					"Write possible solutions.", "Details Error." },
			{
					"1401",
					"Invalid session fault.",
					"Your session is invalid. Please logon to the Metatude Dialogue Server again.",
					"Session timeout." },
			{ "1402", "Directory exists.",
					"Please specify a unique directory name.",
					"Directory name already exists." },
			{ "1403", "Directory not empty.",
					"The directory you selected is not empty.",
					"Directory is not empty." },
			{ "1404", "Driver not found.",
					"Please enter the correct driver name.",
					"Invalid driver or driver not supported." },
			{
					"1405",
					"Incompatible MDD Version.",
					"Please check your MDD dialogue version for MDS compatibility.  Contact Metatude support team for details.",
					"Dialogue version (MDD) is not supported by this server." },
			{
					"1406",
					"Incompatible MPM Version.",
					"The current version of Metatude Project Manager is incompatible with the Metatude Dialogue Server. Please Contact Metatude BV, Amsterdam for information on the latest updates.",
					"MPM version is not supported by this server." },
			{ "1407", "Invalid directory name.",
					"Please specify a valid directory name.",
					"Directory name is not valid." },
			{ "1408", "Invalid password.",
					"Please enter the correct password.", "Password mismatch." },
			{ "1409", "Invalid project status conversion.",
					"Requested conversion is not allowed for the project.",
					"Invalid project status conversion." },
			{
					"1410",
					"Invalid query format.",
					"Ensure the query is valid. Ensure that the database and table is reachable.",
					"Unable to execute the query." },
			{
					"1411",
					"Invitation and interval mismatched.",
					"Please check the Invitation and interval duration. Try to increase or decrease one of them.",
					"Invitation and interval mismatched." },
			{
					"1412",
					"Missing value error.",
					"Please provide all necessary inputs. Make sure you do not keep any required field empty.",
					"A required field is found empty." },
			{
					"1413",
					"Value exceeds maximum allowable storage length.",
					"Please insert a value less or equal to maximum allowable storage length.",
					"Can not insert a value more than the allowable maximum storage length." },
			{
					"1414",
					"Unknown rights fault.",
					"You have a rights limitation for the action. Please logon as Administrator.",
					"A User has some rights limitation for the action." },
			{
					"1415",
					"Completed project.",
					"Try to modify a completed project. You can only delete a completed project.",
					"You can not change the status of a completed project." },
			{
					"1416",
					"Unable to connect to directory server.",
					"The database may not be running and reachable from your machine. Please ensure that you have provided valid values to connect the table and the database.",
					"Directory server can not be connected." },
			{ "1417", "Dialogue does not exist.",
					"Please refresh the tab and try again.",
					"Dialogue not found." },
			{ "1418", "Directory does not exist.",
					"Please refresh the tab and try again.",
					"Directory not found." },
			{
					"1419",
					"Unknown directory server.",
					"Directory server may be deleted by other user. Refresh the directory server tab and try again.",
					"Unknown directory server." },
			{ "1420", "Unknown Invitation.", "Invitation does not exist.",
					"Invitation is unknown to server." },
			{ "1421", "Unknown MDS fault.",
					"Please contact the Metatude BV for further details.",
					"Unknown MDS fault." },
			{ "1422", "Project does not exist.",
					"Please refresh the tab and try again.",
					"Project not Found, may be the project is deleted by some other user." },
			{ "1423", "Unknown rights fault.",
					"You have a rights limitation for the action.",
					"Unknown rights fault." },
			{ "1424", "Unknown server fault.",
					"Please contact the Metatude BV for further details.",
					"Unknown server fault." },
			{ "1425", "No directory server fault.",
					"Please refresh the Directory server tab.",
					"The directory server may be deleted by other user." },
			{
					"1426",
					"Feedback for Database option Fault.",
					"MDS does not support Feedback for Database option, please check your license key.",
					"You may need to get a valid license key." },

			// // Common Faults (1400 - 1599) Class: CFault (Base class)
			// { "1400", "Write Description for Common",
			// "Write possible solutions", "Details Error"},
			// { "1401", "Invalid session fault.", "Please reconnect to MDS.",
			// "Session timeout."},
			// { "1402", "Directory not empty.",
			// "Please delete the directory contains.",
			// "Directory is not empty"},
			// { "1404", "Driver not found.",
			// "Please enter the correct driver name.",
			// "Driver not present in the list"},
			// { "1404", "Incompatible dialogue version.",
			// "Please check your dialogue version.",
			// "May be you have try to upload the wrong dialogue."},
			// { "1405", "Incompatible MPM Version.",
			// "Please check your MPM version for MDS compatibility.",
			// "Version miss match for MPM and MDS."},
			// { "1406", "Invalid directory name.",
			// "Please specify a valid directory name.",
			// "Invalid directory name."},
			// { "1407", "Invalid password.",
			// "Please enter the correct password.", "password miss match."},
			// { "1408", "Edit option unavailable.",
			// "you are not allowed to change the current status.",
			// "Details Error."},
			// { "1409", "Invalid query format",
			// "MPM has sent an invalid query format.",
			// "MPM has sent a invalid query."},
			// { "1410", "Missing value.",
			// "Message may not contain the all necessary fields.",
			// "Details Error."},
			// { "1411", "Invalid DB String field size.",
			// "Please check your DB string field size.", "Details Error."},
			// { "1412", "Invalid administration rights.",
			// "Please check the administrator rights.", "Details Error."},
			// { "1413", "Directory server not found.",
			// "Please check the correct information's that you have provided for the directory server.",
			// "Details Error."},
			// { "1414", "Completed project.",
			// "Try to modify a completed project.", "Details Error."},
			// { "1415", "Unable to connect to a new directory server.",
			// "Please check the in formations for the new directory server.",
			// "Details Error."},
			// { "1416", "Last target group fault.",
			// "Last target group can not be delete from the target group list.",
			// "Details Error."},
			// { "1417", "Dialogue does not exists.",
			// "Please refresh the tab and try again.", "Dialogue not found."},
			// { "1418", "Directory does not exist.",
			// "Please refresh the tab and try again.", "Directory not found."},
			// { "1419", "Unable to modify the target group.",
			// "May be the target group is assign to a project.",
			// "Details Error"},
			// { "1420", "Unknown dialogue.",
			// "May be the dialogue no longer exists.", "Details Error"},
			// { "1421", "Unknown directory.",
			// "Directory not found, refresh the tab and try again.",
			// "Details Error"},
			// { "1422", "Project Does not exist.",
			// "Please refresh the tab and try again.","Project not Found"},
			// { "1423", "Unknown directory server.",
			// "Directory server may be deleted by other user.",
			// "Details Error"},
			// { "1424", "Unknown Invitation.", "Invitation does not exist.",
			// "Details Error"},
			// { "1425", "Unknown MDS fault.",
			// "Please contact the Metautde BV for further details.",
			// "Details Error"},
			// { "1426", "Unknown rights fault.",
			// "You have a rights limitation for the action.", "Details Error"},
			// { "1427", "Unknown server fault.",
			// "Please contact the Metatude BV for further details.",
			// "Details Error"},

			// Users Faults (2000 - 2199) Class: CUserFaults
			{ "2000", "Last admin could not be deleted.",
					"Please create another user, then delete.",
					"User you are trying to delete is the last in the application." },
			{ "2001", "Number of users exceeded.",
					"You may upgrade your license key.",
					"Your license key doesn't support more users to be added." },
			{ "2002", "Unknown user.",
					"This user ID is not available in the database.",
					"This user may be deleted." },
			{ "2003", "User is in use by other user.",
					"Please let the user released.",
					"Other user may work on the same place." },
			{ "2004", "User already exists.",
					"Please write different user name.",
					"This user name already exists in the database." },
			{ "2005", "Write Description for Users.",
					"Write possible solutions.", "Details Error." },

			// DirServers Faults (3000 - 3199) Class: CDirServerFaults
			{ "3000", "Directory server error.",
					"Please contact Metatude support team.",
					"Directory server error." },
			{
					"3001",
					"Empty value is not allowed for value or translation.",
					"Please make sure that the values being entered are not empty.",
					"Value Translation can not be empty." },
			{ "3002", "The directory server is currently in use.",
					"Please try again later.",
					"The directory server is currently in use." },
			{ "3003", "Directory server is currently locked.",
					"Please try later when the lock is released.",
					"Directory server is currently locked." },
			{ "3004", "Directory server name exists.",
					"Please give a unique directory server name.",
					"Directory server name already exists." },
			{
					"3005",
					"Duplicate value/translation specified.",
					"Value/translation should always be unique. So you must insert unique value for value translation.",
					"Duplicate value/translation not allowed." },
			{ "3006", "Lookup table can not be used with LDAP Server.",
					"Lookup table feature is only allowed with JDBC server.",
					"Lookup table feature can not be used with LDAP Server." },
			{
					"3007",
					"Invalid port.",
					"Please specify a valid port number. Port numbers should be non-negative whole numbers.",
					"Invalid LDAP port specified." },
			{
					"3008",
					"Invalid Lookup table information.",
					"Please make sure that the table information entered is valid.",
					"Lookup table information not valid." },
			{
					"3009",
					"Limit of JDBC server connection exceeded.",
					"You can either delete unused JDBC directory servers or update your license key to increase your JDBC connection limit.",
					"License limitation error: Number of allowed JDBC server connection exceeded." },
			{
					"3010",
					"Limit of LDAP server connection exceeded.",
					"You can either delete unused LDAP directory servers or update your license key to increase your JDBC connection limit.",
					"License limitation error: Number of allowed LDAP server connection exceeded." },
			{
					"3011",
					"Number of stakeholders exceeds the limit allowed by the license.",
					"You can either delete unused directory servers or update your license key to increase your stakeholders limit.",
					"License limitation error: Number of stakeholders exceeds the limit allowed by the license." },
			{ "3012", "Unknown protocol error.",
					"Please contact Metatude support team.",
					"Unknown protocol error." },
			{ "3013", "Value/Translation cannot be empty.",
					"Please make sure that the values entered are not empty.",
					"Value Translation can not be empty." },

			// CustomAttribute Faults (3200 - 3249) Class: CDirServerFaults
			{ "3200", "Custom attribute error.",
					"Please contact Metatude support team.",
					"Custom attribute error." },
			{ "3201", "Custom attribute is currently locked.",
					"Please try later when the lock is released.",
					"Custom attribute is currently locked." },
			{ "3202", "Custom attribute name exists.",
					"Please give a unique custom attribute name.",
					"Custom attribute name already exists." },
			{
					"3203",
					"Invalid custom attribute name specified.",
					"A custom attribute name cannot be blank or cannot contain more than 255 characters."
							+ "It cannot have same name as base data types i.e. String, Date, Number, Boolean as well as reserved attributes"
							+ "i.e. Url, User, Name and Email. Please specify a valid name, regardless of case differences.",
					"Invalid custom attribute name specified." },
			{
					"3204",
					"Custom attribute record not found.",
					"Please try again. Make sure the database is running properly. Record may be modified or deleted.",
					"Error retrieving custom attributes records." },

			// TargetGroups Faults (4000 - 4199) Class: CTargetGroupsFaults
			{ "4000", "General error in target group.",
					"Please try again later.",
					"There might have some errors in target group." },
			{
					"4001",
					"The target group is currently in use.",
					"To change/delete any target group, remove the target group from any project it is assigned to.",
					"When a target group is assigned to a project, edit or delete is not allowed." },
			{
					"4002",
					"The target group is locked by another user.",
					"Please refresh the window and try again.",
					"Another client might be updating this window. More than one person is not allowed to edit the content of this window simultaneously." },
			{
					"4003",
					"Target group name exists.",
					"Specify a different name.",
					"A target group with the name you specified already exists. Specify a different name." },
			{ "4004", "Unknown target group error.", "Refresh and try again.",
					"Target group record is unknown or could not be retrieved." },

			// Projects Faults (5000 - 5199) Class: CProjectFaults
			{ "5000", "Write Description for project",
					"Write possible solutions", "Details Error" },
			{
					"5001",
					"End date of the project is already passed.",
					"End date of the project is already passed, This is not editable project.",
					"End date of the project is over." },
			{ "5002", "Active project could not be deleted.",
					"Make the project completed, then delete.", "Details Error" },
			{ "5003", "Paused project could not be deleted.",
					"Make the project completed, then delete.", "Details Error" },
			{ "5004", "Write Description for project",
					"Write possible solutions", "Details Error" },
			{ "5005", "End date of the project is not applicable.",
					"Please insert applicable end date.", "Details Error" },
			{ "5006", "Write Description for project",
					"Write possible solutions", "Details Error" },
			{
					"5007",
					"Interval type could not be modified after activation of the project.",
					"Please create new project with required interval.",
					"After sending mail, Interval type of the project couldn't be modified." },
			{ "5008", "Start at date of the project is not valid.",
					"Please insert valid start date.", "Details Error" },
			{ "5009", "Project is locked.", "Let the project unlocked.",
					"This project is locked by another user." },
			{ "5010", "Project already exists.",
					"Choose different project name.",
					"Project name should be unique, project given by you already exist." },
			{ "5013", "Unable to modify Paused Project.",
					"Change the status and try again.",
					"This paused project could not be modified." },
			{ "5014", "Unable to delete last target group.",
					"Please keep at least one target group.",
					"There should be at least one target group." },
			{ "5015", "Unable to modify Target group of the project.",
					"Check whether project is completed or not.",
					"Target group could not be modified now." },
			{
					"5016",
					"Template uses this project. This project can not be deleted.",
					"Release project from Template and try again.",
					"If any Template uses a project, that project can not be deleted until it is released from the Template." },
			{
					"5017",
					"Template uses this project. This project can not be deleted.",
					"Release project from Template and try again.",
					"If any Template uses a project, that project can not be deleted until it is released from the Template." },

			// Dialogues Faults (5400 - 5599) Class: CDialogueFaults
			{ "5400", "Write Description dlg", "Write possible solutions",
					"Details Error" },
			{ "5401", "Write Description dlg", "Write possible solutions",
					"Details Error" },
			{ "5402", "Structure table could not be created.",
					"Please try again.",
					"Internal fault while creating structure table." },
			{
					"5403",
					"Dialogue is in use. ",
					"Dialogue can be deleted when it is not in use by any project.",
					"One or more projects are using this dialogue." },
			{
					"5404",
					"Dialogue can not be modified.",
					"Dialogue is only allowed to modify before sending invitation.",
					"Dialogue can not be modified once any mail is sent for the project." },
			{ "5405", "Language not supported.",
					"Please contact Metatude support team.",
					"Language not supported." },

			// Invitations Faults (5600 - 5799) Class: CInvitationFaults
			{ "5600", "General error in Invitation.",
					"Please try again later.",
					"There might have some errors in invitation." },
			{
					"5601",
					"Invitation is currently in use.",
					"When an invitation is assigned to a project, delete operation on it is not allowed.",
					"When an invitation is assigned to a project, delete operation on it is not allowed." },
			{ "5602",
					"Invitation can not be modified once the mails are sent.",
					"Create a new project with new invitation.",
					"Invitation text can not be modified after mails are sent. " },

			// Reminders Faults (5800 - 5999) Class: CReminderFaults
			{ "5800", "General error in reminders.", "Please try again later.",
					"There might have some errors in reminders." },
			{ "5801", "Error while adding reminders.",
					"Please try again later.",
					"Unknown error occurred while adding reminder." },
			{ "5802", "Unknown reminder.",
					"Please refresh the list and try again.",
					"Other user may change/delete the reminder which you are trying to change." },
			{ "5803", "Reminder name can not be null.",
					"Please provide a valid non empty reminder name.",
					"Reminder name is empty. There must have a valid reminder name." },
			{
					"5804",
					"The reminder name exists.",
					"Specify a different name.",
					"A reminder with the name you specified already exists. Specify a different name." },
			{ "5805", "Reminder email can not be null.",
					"Please provide a valid non empty email address.",
					"Reminder email is empty. There must have a valid reminder email." },
			{ "5806", "Remind after value can not be null.",
					"Please provide a valid non empty remind after value.",
					"Remind after value is empty. There must have a valid remind after value." },
			{ "5807", "Reminder subject can not be null.",
					"Please provide a valid non empty reminder subject.",
					"Reminder subject is empty. There must have a valid reminder subject." },
			{ "5808", "Reminder body can not be null.",
					"Please provide a valid non empty reminder body.",
					"Reminder body is empty. There must have a valid reminder body." },
			{
					"5809",
					"Reminder after value is invalid.",
					" 1. Use a positive number. \n 2. Use unique number for each remind after value in a project."
							+ "\n 3. For CR project, use remind after value smaller than interval duration.",
					"This fault may occur for the following reasons: \n 1. Remind after must not be null, zero or negative."
							+ "\n 2. It is not allowed to have more than one reminder with same start date in a project."
							+ "\n 3. For CR project, remind after value must be smaller than interval duration." },
			{
					"5810",
					"Remind after value is invalid as it exceeds the end date.",
					"Please select a remind-after value which is smaller than project end date.",
					"This reminder will not remind as project has end date and remind after value exceeds the end date." },
			{
					"5811",
					"The specified remind after value indicates a past date.",
					"Please specify a bigger remind after value.",
					"Remind after date is relative to the project start date. The remind-after needs a value greater than present date." },
			{
					"5812",
					"Status you tried to change is not allowed.",
					"Please try a different status.",
					"Allowed status:  \nScheduled -> Inactive, \nScheduled -> Remind Now, \nIn Progress -> Paused, \nIn Progress -> Completed, "
							+ "\nPaused -> In Progress, \nPaused -> Completed, \nInactive -> Scheduled." },
			{ "5813", "Reminder nature can not be changed.",
					"You can change Once reminder to Repetitive.",
					"Reminder status Repetitive can not be changed to Once." },
			{ "5814", "Reminder not editable.",
					"Completed reminder can not be edited.",
					"Reminder can not be changed now." },
			{ "5815", "Error while deleting reminders.",
					"Please try again later.",
					"Unknown error occurred while deleting reminder." },
			{
					"5816",
					"Status can not be changed to Remind Now when \n 1. There is original/reminder invitations in progress. \n 2. Any reminder of this project has status \'Remind Now\', \'In Progress\' or \'Paused\'.",
					"Please try again later.",
					"Reminder now can not be added when there are pending mails for the project." },

			// Results Faults (6000 - 6199) Class: CResultsFaults
			{ "6000", MsgConst.kRspMsgUnknown, "", "" },
			{ "6001", MsgConst.kRspMsgNoPrj, "", "" },
			{ "6002", MsgConst.kRspMsgAlreadySub, "", "" },

			// Respondents (6200 - 6399) Class: CResultsFaults
			{ "6200", "Number Of Monthly Respondents is Exceeded.",
					"Write possible solutions", "Details Error" },
			{ "6201", MsgConst.kRspMsgWereInv, "Write possible solutions",
					"Details Error" },
			{ "6202", MsgConst.kRspMsgNoAccessResultTbl,
					"Write possible solutions", "Details Error" },
			{ "6203", MsgConst.kRspMsgNoResultTbl, "Write possible solutions",
					"Details Error" },
			{ "6204", MsgConst.kRspMsgNoDlg, "Write possible solutions",
					"Details Error" },
			{ "6205", MsgConst.kRspMsgNoPrj, "Write possible solutions",
					"Details Error" },
			{ "6206", MsgConst.kRspMsgCompletedProject,
					"Write possible solutions", "Details Error" },
			{ "6207", MsgConst.kRspMsgUnknownMCICVersion,
					"Write possible solutions", "Details Error" },

			// Destination DB Faults (7000 - 7199) Class: CFFDFaults
			{
					"7000",
					"Destination DB Error.",
					"Please contact the Metatude support team for further details.",
					"Destination DB Error." },
			{ "7001", "Destination DB name already exists.",
					"Please give a unique Destination DB name.",
					"Destination DB name already exists." },
			{
					"7002",
					"Destination DB record not found.",
					"Refresh and try again.",
					"Destination DB record not found. Related record can not be retrieved or record may be deleted or modified." },
			{ "7003", "Unable to connect Destination DB.",
					"Please provide valid database information and try again.",
					"Could not connect to external database." },
			{ "7004", "Destination DB is currently locked.",
					"Please try later when the lock is released.",
					"Destination DB is locked by another user." },
			{
					"7005",
					"Destination DB is in use.",
					"Destination DB can't not be modified or deleted when it is used by Database feedback template. Delete the related Template before trying to modify/delete the Destination DB.",
					"Destination DB is in use by one or more Templates." },
			{
					"7006",
					"Table name not found.",
					"Please provide valid table name and database information and try again.",
					"Unable to connect Destination DB. Table name not found." },

			// Template Faults (7200 - 7399) Class: CFFDFaults
			{
					"7200",
					"Template Error.",
					"Please contact the Metatude support team for further details.",
					"Template Error." },
			{
					"7201",
					"Directory can not contain more than one similar Template name.",
					"Please choose another Template name or rename Template name to a different one.",
					"Similar Template name already exists in the directory." },
			{ "7202", "Template does not exist.",
					"Please refresh the list and try again.",
					"Directory not found." },
			{ "7203", "Active Template can not be deleted.",
					"Please Make the Template inactive then delete it.",
					"Details error is not available." },
			{
					"7204",
					"Template is locked.",
					"Let the session time out or Check Other user's activities.",
					"Template is locked, Couldn't be deleted." },
			{ "7205", "Template name is Empty.",
					"Please give a valid Template name and Add Again.",
					" Template name field is empty." },
			{ "7206", "Template test Fault.",
					"Please review the Template mapping with Database issues.",
					"More information available in the error log file." },
			{ "7207", "Update criteria is a must.", "Please define a rule.",
					"Update criteria is required to save any Template in update mode." },
			{
					"7208",
					"Mapping of External Data Source (Destination DB) should be defined.",
					"Please define a Destination DB mapping.",
					"Attribute Mapping is required to save the Template." },
			{ "7209", "There may be error in mapping.",
					"Please check the mapping and try again.",
					"There may be parameter missing in mapping." }, };

}
